### PR TITLE
Russian language addition

### PR DESCRIPTION
**Pull request by Golosovoy**
# Russian Addition/Modification

## I have verified that

- Every argument variable (`{0}`, `{1}`, ...) remained the same.
- There isn't an other pull request with the same language.
- I escaped every double quote with a backslash (`"` -> `\"`).
- I have **not** modified any keys such as `SELECT_ROLES`.
- The JSON syntax is valid.

### CODE REVIEW

**Comment by ZeldaFan0225** [comment]
The strings for

`DROPDOWNROLES_ADVANCED_MODAL_ROLE_LABEL`
and
`DROPDOWNROLES_ADVANCED_MODAL_RESTRICTION_PLACEHOLDER`

exceed discords character limit of 40...
Please make them be 40 or below

**Review by ZeldaFan0225 — CHANGES_REQUESTED** [review]
L304 and L311 need to be shortened to be 40 or less characters in length

**Comment by ZeldaFan0225** [comment]
translate the key
`ERROR_BUTTONROLE_MISSING_ROLE1`

as "<:SystemMessageInteractionFail:872222564557127680> You're missing the role <@&{0}> to add/remote the role(s) {2} to/from yourself."

**Comment by Golosovoy** [comment]
Key `ERROR_BUTTONROLE_MISSING_ROLE1` also was translated

**Review by ZeldaFan0225 — APPROVED** [review]

**Pull request closed without merging**
